In [1]:
import pandas as pd
import numpy as np

In [2]:
books = pd.read_csv('data/Books.csv')
users = pd.read_csv('data/Users.csv')
ratings = pd.read_csv('data/Ratings.csv')

C:\Users\kumar\AppData\Local\Temp\ipykernel_17968\927319382.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('data/Books.csv')

In [3]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [4]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [5]:
users

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [6]:
ratings_with_name = ratings.merge(books, on='ISBN')

In [7]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276704,0876044011,0,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,1998,A.R.E. Press (Association of Research &amp; Enlig,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...
1031132,276704,1563526298,9,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,2000,Longstreet Press,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...
1031133,276706,0679447156,0,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,1997,Alfred A. Knopf,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...
1031134,276709,0515107662,10,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,1996,Jove Books,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...
1031135,276721,0590442449,10,Fourth Grade Rats,Jerry Spinelli,1996,Scholastic,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...

In [8]:
num_ratings_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_ratings_df.rename(columns = {'Book-Rating': 'Num-Rating'}, inplace=True)
num_ratings_df

                                               Book-Title  Num-Rating
0        A Light in the Storm: The Civil War Diary of ...           4
1                                   Always Have Popsicles           1
2                    Apple Magic (The Collector's series)           1
3        Ask Lily (Young Women of Faith: Lily Series, ...           1
4        Beyond IBM: Leadership Marketing and Finance ...           1
...                                                   ...         ...
241066                                      Ãƒ?Ã‚?lpiraten.           2
241067                     Ãƒ?Ã‚?rger mit Produkt X. Roman.           4
241068                                Ãƒ?Ã‚?sterlich leben.           1
241069                              Ãƒ?Ã‚?stlich der Berge.           3
241070                                  Ãƒ?Ã‚?thique en toc           2

[241071 rows x 2 columns]

In [9]:
avg_ratings_df = ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_ratings_df.rename(columns={'Book-Rating': 'Avg-Ratings'}, inplace=True)
avg_ratings_df

                                               Book-Title  Avg-Ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ãƒ?Ã‚?lpiraten.     0.000000
241067                     Ãƒ?Ã‚?rger mit Produkt X. Roman.     5.250000
241068                                Ãƒ?Ã‚?sterlich leben.     7.000000
241069                              Ãƒ?Ã‚?stlich der Berge.     2.666667
241070                                  Ãƒ?Ã‚?thique en toc     4.000000

[241071 rows x 2 columns]

In [10]:
final_df = avg_ratings_df.merge(num_ratings_df, on='Book-Title')
final_df.rename(columns={'Avg-Ratings':'Avg-Rating'}, inplace=True)
final_df

,Book-Title,Avg-Rating,Num-Rating
0,A Light in the Storm: The Civil War Diary of ...,2.250000,4
1,Always Have Popsicles,0.000000,1
2,Apple Magic (The Collector's series),0.000000,1
3,"Ask Lily (Young Women of Faith: Lily Series, ...",8.000000,1
4,Beyond IBM: Leadership Marketing and Finance ...,0.000000,1
...,...,...,...
241066,Ãƒ?Ã‚?lpiraten.,0.000000,2
241067,Ãƒ?Ã‚?rger mit Produkt X. Roman.,5.250000,4
241068,Ãƒ?Ã‚?sterlich leben.,7.000000,1
241069,Ãƒ?Ã‚?stlich der Berge.,2.666667,3
241070,Ãƒ?Ã‚?thique en toc,4.000000,2

In [11]:
final_df = final_df[final_df['Num-Rating'] >= 200]
final_df.sort_values('Avg-Rating', ascending=False, inplace=True)
final_df.head(50)

C:\Users\kumar\AppData\Local\Temp\ipykernel_17968\3876913250.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.sort_values('Avg-Rating', ascending=False, inplace=True)

,Book-Title,Avg-Rating,Num-Rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),5.852804,428
80422,Harry Potter and the Goblet of Fire (Book 4),5.824289,387
80441,Harry Potter and the Sorcerer's Stone (Book 1),5.737410,278
80426,Harry Potter and the Order of the Phoenix (Boo...,5.501441,347
60582,Ender's Game (Ender Wiggins Saga (Paperback)),5.409639,249
80414,Harry Potter and the Chamber of Secrets (Book 2),5.183453,556
191612,The Hobbit : The Enchanting Prelude to The Lor...,5.007117,281
187377,The Fellowship of the Ring (The Lord of the Ri...,4.948370,368
80445,Harry Potter and the Sorcerer's Stone (Harry P...,4.895652,575
211384,"The Two Towers (The Lord of the Rings, Part 2)",4.880769,260
219741,To Kill a Mockingbird,4.700000,510
183573,The Da Vinci Code,4.642539,898
187880,The Five People You Meet in Heaven,4.551163,430
180556,The Catcher in the Rye,4.545657,449
204672,"The Return of the King (The Lord of the Rings,...",4.497630,211
196326,The Lovely Bones: A Novel,4.468726,1295
190081,The Great Gatsby,4.458537,205
764,1984,4.454225,284
144165,Prodigal Summer: A Novel,4.450593,253
128670,Neverwhere,4.449057,265
206502,The Secret Life of Bees,4.447028,774
168719,Stupid White Men ...and Other Sorry Excuses fo...,4.356890,283
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",4.354970,493
204387,The Red Tent (Bestselling Backlist),4.334716,723
27295,Brave New World,4.331858,226
191589,The Hitchhiker's Guide to the Galaxy,4.328358,268
129379,Nickel and Dimed: On (Not) Getting By in America,4.289552,335
209778,The Tao of Pooh,4.289100,211
14607,Animal Farm,4.274678,233
93381,Into the Wild,4.273810,252
63867,Fahrenheit 451,4.264059,409
7373,A Walk in the Woods: Rediscovering America on ...,4.243902,205
74750,Girl with a Pearl Earring,4.218631,526
129444,Night,4.217822,202
136145,Outlander,4.173145,283
209209,"The Subtle Knife (His Dark Materials, Book 2)",4.124444,225
181699,The Color of Water: A Black Man's Tribute to H...,4.107623,223
233370,Where the Heart Is (Oprah's Book Club (Paperba...,4.105983,585
156102,Seabiscuit: An American Legend,4.098182,275
107962,Life of Pi,4.088855,664
176845,The Bean Trees,4.087404,389
2281,"A Child Called \It\"": One Child's Courage to S...",4.086792,265
8434,ANGELA'S ASHES,4.075269,279
83432,High Fidelity,4.056680,247
76343,Good in Bed,4.055102,490
64931,Fast Food Nation: The Dark Side of the All-Ame...,4.037383,321
12700,American Gods,4.006623,302
161645,Skipping Christmas,4.006211,322
105777,Left Behind: A Novel of the Earth's Last Days ...,4.003145,318
189551,"The Golden Compass (His Dark Materials, Book 1)",4.000000,336

In [20]:
popular_books_df = final_df.merge(books, on='Book-Title')
popular_books_df

,Book-Title,Avg-Rating,Num-Rating,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,Harry Potter and the Prisoner of Azkaban (Book 3),5.852804,428,0439136350,J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...
1,Harry Potter and the Prisoner of Azkaban (Book 3),5.852804,428,0439136369,J. K. Rowling,2001,Scholastic,http://images.amazon.com/images/P/0439136369.0...,http://images.amazon.com/images/P/0439136369.0...,http://images.amazon.com/images/P/0439136369.0...
2,Harry Potter and the Prisoner of Azkaban (Book 3),5.852804,428,0786222743,J. K. Rowling,2000,Thorndike Press,http://images.amazon.com/images/P/0786222743.0...,http://images.amazon.com/images/P/0786222743.0...,http://images.amazon.com/images/P/0786222743.0...
3,Harry Potter and the Goblet of Fire (Book 4),5.824289,387,0439139597,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...
4,Harry Potter and the Goblet of Fire (Book 4),5.824289,387,0439139600,J. K. Rowling,2002,Scholastic Paperbacks,http://images.amazon.com/images/P/0439139600.0...,http://images.amazon.com/images/P/0439139600.0...,http://images.amazon.com/images/P/0439139600.0...
...,...,...,...,...,...,...,...,...,...,...
1127,Slow Waltz in Cedar Bend,1.895161,248,0446516538,Robert James Waller,1993,Warner Books,http://images.amazon.com/images/P/0446516538.0...,http://images.amazon.com/images/P/0446516538.0...,http://images.amazon.com/images/P/0446516538.0...
1128,Slow Waltz in Cedar Bend,1.895161,248,074932032X,Robert James Waller,1995,Mandarin,http://images.amazon.com/images/P/074932032X.0...,http://images.amazon.com/images/P/074932032X.0...,http://images.amazon.com/images/P/074932032X.0...
1129,Slow Waltz in Cedar Bend,1.895161,248,0749317647,Robert James Waller,1995,Mandarin,http://images.amazon.com/images/P/0749317647.0...,http://images.amazon.com/images/P/0749317647.0...,http://images.amazon.com/images/P/0749317647.0...
1130,Songs in Ordinary Time (Oprah's Book Club (Pap...,1.857759,232,0140244824,Mary McGarry Morris,1996,Penguin Books,http://images.amazon.com/images/P/0140244824.0...,http://images.amazon.com/images/P/0140244824.0...,http://images.amazon.com/images/P/0140244824.0...
1131,Wild Animus,1.019584,2502,0971880107,Rich Shapero,2004,Too Far,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...

In [23]:
popular_books_df = popular_books_df[['Book-Title', 'Avg-Rating', 'Num-Rating', 'Book-Author']].head(50)

In [21]:
popular_books_df.columns

Index(['Book-Title', 'Avg-Rating', 'Num-Rating', 'ISBN', 'Book-Author',
       'Year-Of-Publication', 'Publisher', 'Image-URL-S', 'Image-URL-M',
       'Image-URL-L'],
      dtype='object')

In [22]:
popular_books_df = popular_books_df.drop_duplicates(subset='Book-Title')[['Book-Title', 'Book-Author', 'Image-URL-M', 'Num-Rating', 'Avg-Rating']]

In [24]:
popular_books_df

,Book-Title,Avg-Rating,Num-Rating,Book-Author
0,Harry Potter and the Prisoner of Azkaban (Book 3),5.852804,428,J. K. Rowling
3,Harry Potter and the Goblet of Fire (Book 4),5.824289,387,J. K. Rowling
5,Harry Potter and the Sorcerer's Stone (Book 1),5.737410,278,J. K. Rowling
9,Harry Potter and the Order of the Phoenix (Boo...,5.501441,347,J. K. Rowling
13,Ender's Game (Ender Wiggins Saga (Paperback)),5.409639,249,Orson Scott Card
17,Harry Potter and the Chamber of Secrets (Book 2),5.183453,556,J. K. Rowling
20,The Hobbit : The Enchanting Prelude to The Lor...,5.007117,281,J.R.R. TOLKIEN
21,The Fellowship of the Ring (The Lord of the Ri...,4.948370,368,J.R.R. TOLKIEN
30,Harry Potter and the Sorcerer's Stone (Harry P...,4.895652,575,J. K. Rowling
32,"The Two Towers (The Lord of the Rings, Part 2)",4.880769,260,J.R.R. TOLKIEN
43,To Kill a Mockingbird,4.700000,510,Harper Lee
51,The Da Vinci Code,4.642539,898,Dan Brown
57,The Five People You Meet in Heaven,4.551163,430,Mitch Albom
59,The Catcher in the Rye,4.545657,449,J.D. Salinger
66,"The Return of the King (The Lord of the Rings,...",4.497630,211,J.R.R. TOLKIEN
76,The Lovely Bones: A Novel,4.468726,1295,Alice Sebold
77,The Great Gatsby,4.458537,205,F. Scott Fitzgerald
79,1984,4.454225,284,George Orwell
88,Prodigal Summer: A Novel,4.450593,253,Barbara Kingsolver
89,Neverwhere,4.449057,265,Neil Gaiman
94,The Secret Life of Bees,4.447028,774,Sue Monk Kidd
100,Stupid White Men ...and Other Sorry Excuses fo...,4.356890,283,Michael Moore
101,"Tuesdays with Morrie: An Old Man, a Young Man,...",4.354970,493,MITCH ALBOM
104,The Red Tent (Bestselling Backlist),4.334716,723,Anita Diamant
105,Brave New World,4.331858,226,Aldous Huxley
110,The Hitchhiker's Guide to the Galaxy,4.328358,268,Douglas Adams
119,Nickel and Dimed: On (Not) Getting By in America,4.289552,335,Barbara Ehrenreich
121,The Tao of Pooh,4.289100,211,Benjamin Hoff
123,Animal Farm,4.274678,233,George Orwell
133,Into the Wild,4.273810,252,Jon Krakauer
136,Fahrenheit 451,4.264059,409,Ray Bradbury
149,A Walk in the Woods: Rediscovering America on ...,4.243902,205,Bill Bryson
150,Girl with a Pearl Earring,4.218631,526,Tracy Chevalier
151,Night,4.217822,202,Elie Wiesel
156,Outlander,4.173145,283,DIANA GABALDON
162,"The Subtle Knife (His Dark Materials, Book 2)",4.124444,225,PHILIP PULLMAN
170,The Color of Water: A Black Man's Tribute to H...,4.107623,223,James McBride
172,Where the Heart Is (Oprah's Book Club (Paperba...,4.105983,585,Billie Letts
173,Seabiscuit: An American Legend,4.098182,275,LAURA HILLENBRAND
175,Life of Pi,4.088855,664,Yann Martel
179,The Bean Trees,4.087404,389,Barbara Kingsolver
182,"A Child Called \It\"": One Child's Courage to S...",4.086792,265,Dave Pelzer
184,ANGELA'S ASHES,4.075269,279,Frank McCourt
186,High Fidelity,4.056680,247,Nick Hornby
192,Good in Bed,4.055102,490,Jennifer Weiner
194,Fast Food Nation: The Dark Side of the All-Ame...,4.037383,321,Eric Schlosser
195,American Gods,4.006623,302,Neil Gaiman
196,Skipping Christmas,4.006211,322,JOHN GRISHAM
202,Left Behind: A Novel of the Earth's Last Days ...,4.003145,318,Tim Lahaye
204,"The Golden Compass (His Dark Materials, Book 1)",4.000000,336,PHILIP PULLMAN